services:
  db:
    image: postgres:14.18
    container_name: lms-backend-db-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2003 
    ports:
      - 5433:5432
    volumes:
      - "lms_backend_data:/var/lib/postgresql/data"
    networks:
      - lms_backend_network

  redis:
    image: redis:6.0.7
    container_name: redis-edu
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
    networks:
      lms_backend_network:
        aliases:
          - redis-local

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight-edu
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - redis_insight_volume_data:/db
    depends_on:
      - redis
    networks:
      - lms_backend_network

  storage:
    image: minio/minio:latest
    container_name: minio-edu
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "@Password123!"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - storage:/data
    networks:
      - lms_backend_network


  backend:
    build: .
    container_name: lms-backend-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lms-backend-db-container:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 2003
      MINIO_URL: http://minio-edu:9000
      MINIO_USERNAME: admin
      MINIO_PASSWORD: "@Password123!"
      MINIO_BUCKET_NAME: common
      SPRING_DATA_REDIS_HOST: redis-edu
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - 8081:8090
    depends_on:
      - db
      - storage
      - redis
    networks:
      - lms_backend_network

networks:
  lms_backend_network:
    driver: bridge

volumes:
  redis_volume_data:
  redis_insight_volume_data:
  lms_backend_data:
  storage: